// Typed view of the generated credential manifests, imported (not copied) so
// the dashboard, the CLI (apps/cli/src/manifest.ts) and the runtime scripts
// share one source of truth:
//   harness-adapter/harnesses.json  per-harness credentials, most preferred
//                                   first, plus token_usage and default_model
//   harness-adapter/gateways.json   the claude harness's LLM-gateway cascade
// Both are generated by harness-adapter/bin/generate-harnesses-json and held
// to the scripts by scripts/tests/test_credential_manifest.sh. PURE: safe in
// client components (the JSON is bundled at build time).
import harnessesJson from '../../../harness-adapter/harnesses.json'
import gatewaysJson from '../../../harness-adapter/gateways.json'

export type CredentialKind = 'oauth_capture' | 'oauth_token' | 'api_key' | 'oidc'

export interface ManifestCredential {
  secret: string
  kind: CredentialKind
  auth_mode: 'native-oauth' | 'native-key' | 'openrouter'
  label: string
  prefix?: string
  get_url: string
  login_cmd?: string
  aeon_cmd?: string
  cred_paths?: string[]
  expires?: string
  refresh?: string
  aux_secrets?: string[]
}

export interface ManifestHarness {
  id: string
  label: string
  // 'none': the harness reports no real token counts (0 or an estimate).
  token_usage: 'full' | 'partial' | 'none' | string
  default_model: string
  credentials: ManifestCredential[]
  gateways?: string
}

export interface ManifestGateway {
  id: string
  label: string
  secrets: string[]
  prefixes: string[]
  transport: 'native' | 'anthropic-compatible' | 'sidecar'
  base_url: string
  get_url: string
}

export const MANIFEST_HARNESSES = (harnessesJson as unknown as { harnesses: ManifestHarness[] }).harnesses
export const MANIFEST_GATEWAYS = (gatewaysJson as unknown as { gateways: ManifestGateway[] }).gateways

export function harnessManifest(id: string): ManifestHarness | undefined {
  return MANIFEST_HARNESSES.find((h) => h.id === id)
}

export function credentialsFor(id: string): ManifestCredential[] {
  return harnessManifest(id)?.credentials ?? []
}
