// Typed reader for the generated credential manifests:
//   harness-adapter/harnesses.json  per-harness credentials (most preferred
//                                   first, exactly as scripts/resolve-harness.sh
//                                   picks them) + default_model
//   harness-adapter/gateways.json   the claude harness's LLM-gateway cascade
// Both are generated by harness-adapter/bin/generate-harnesses-json and held to
// the runtime scripts by scripts/tests/test_credential_manifest.sh, so commands
// read them instead of keeping a third copy of "which secret does what".
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

// The manifests describe THIS checkout's code, so read them from beside the CLI
// rather than from AEON_REPO_ROOT (which may point at another, older repo).
const CLI_REPO = fileURLToPath(new URL('../../..', import.meta.url))

export type CredentialKind = 'oauth_capture' | 'oauth_token' | 'api_key' | 'oidc'

export interface Credential {
  secret: string
  kind: CredentialKind
  auth_mode: 'native-oauth' | 'native-key' | 'openrouter'
  label: string
  prefix?: string
  get_url: string
  login_cmd?: string
  aeon_cmd?: string
  cred_paths?: string[]
  expires?: string
  refresh?: string
  aux_secrets?: string[]
}

export interface HarnessManifest {
  id: string
  label: string
  cli: { install: string; bin: string; min_version: string }
  default_model: string
  credentials: Credential[]
  gateways?: string
}

export interface Gateway {
  id: string
  label: string
  secrets: string[]
  prefixes: string[]
  transport: 'native' | 'anthropic-compatible' | 'sidecar'
  base_url: string
  get_url: string
}

function readJson<T>(rel: string, root: string): T {
  return JSON.parse(readFileSync(join(root, rel), 'utf8')) as T
}

export function loadHarnesses(root = CLI_REPO): HarnessManifest[] {
  return readJson<{ harnesses: HarnessManifest[] }>('harness-adapter/harnesses.json', root).harnesses
}

export function loadGateways(root = CLI_REPO): Gateway[] {
  return readJson<{ gateways: Gateway[] }>('harness-adapter/gateways.json', root).gateways
}

// Every secret that, once set, lets `harness` run: its own credentials, plus
// (claude only) every gateway key in the cascade.
export function runnableSecrets(harness: HarnessManifest, gateways: Gateway[]): string[] {
  const own = harness.credentials.map((c) => c.secret)
  const gw = harness.gateways ? gateways.flatMap((g) => g.secrets) : []
  return [...new Set([...own, ...gw])]
}
